#!/usr/bin/env python
#A System Information Gathering Script

def find_last(string,str):
    last_position=-1
    while True:
        position=string.find(str,last_position+1)
        if position==-1:
            return last_position
        last_position=position

numberList = ['1']
arryList = ['00','01','02','03','04','05','06','07','08','09','10','11','12','13','14','15','16','17','18','19','20','21','22','23','24','25','26','27','28','29','30','31','32','33','34','35','36','37','38','39','40','41','42','43','44','45','46','47','48','49','50','51','51','53','54','55','56','57','58','59']

formList = []
for obj in arryList:
	fileName = "319_queryflight.log"
	try:
		f = open(fileName, "r",errors = 'ignore') 
		first_line = f.readlines() 
		count = 0
		total = 0
		strTongji = '2018:11:18:'+obj
		print(strTongji)
		for x in first_line:
			try:
				if x.find(strTongji)>-1:
					total = total +1
			except Exception as e:
				print(e)
		# print(result)
		f.close() 
	except Exception as e :
		f.close() 
		print(e)
	formList.append(total)


print(formList)
zongshu = 0
for  y in formList:
	zongshu  = zongshu+y

	print(y)


print('总数是',zongshu)
















# commands = command2 + command3
# subprocess.call(commands, shell=True)
# total = 0
# try:
# 	f= open('total.log','r+')
# 	list2 =f.readlines()
# 	print(list2)
# 	# print(list1)
# 	for i in range(0,len(list2)):
# 		if len(str(i))>0:
# 			print(i)
# 			total= total + int(list2[i])
# 	print(total)
# 	f.write('\n')
# 	f.write(str(total))
# finally:
# 	if f:
# 		f.close()



